<?php

namespace App\Orchid\Screens\DRX;


use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
use Orchid\Screen\Fields\CheckBox;
use Orchid\Screen\Fields\DateTimer;
use Orchid\Screen\Fields\Picture;
use Orchid\Screen\Fields\Select;
use Orchid\Screen\Fields\TextArea;
use Orchid\Support\Facades\Layout;
use Orchid\Screen\Fields\Input;
use App\DRX\DRXClient;

class Permission4EmployeeScreen extends SecuritySRQScreen
{
    // Тип документа в сервисе интеграции, например IOfficialDocuments
    protected $EntityType = "IServiceRequestsPermission4Employees";
    public $Title = "Заявка на временный доступ для сотрудника";

    public function beforeSave()
    {
        parent::beforeSave(); // TODO: Change the autogenerated stub
        $this->NormalizeDate(['ValidFrom', 'ValidTill']);
    }

    // Описывает макет экрана
    public function layout(): iterable
    {
        $layout = parent::layout();
        array_pop($layout);
        $layout[] = Layout::rows([
            Input::make("entity.Employee")->title("ФИО сотрудника")->horizontal(),
            Input::make("entity.PassNumber")->title("Номер пропуска сотрудника")->horizontal(),
            DateTimer::make('entity.ValidFrom')->title("Действует с")->horizontal()
                ->min(Carbon::today())->enableTime(false)->format('d-m-Y'),
            DateTimer::make('entity.ValidTill')->title("Действует до")->horizontal()
                ->min(Carbon::today())->enableTime(false)->format('d-m-Y'),
            Input::make('entity.Permisssion')->title("Вид доступа")->horizontal(),
            Select::make('entity.sites')
        ])->title('Описание дополнительного доступа');
        return $layout;
    }
}
