<?php

namespace App\DRX\Screens\Cars;

use App\DRX\Helpers\Databooks;
use App\DRX\Layouts\PermanentPass4CarListener;
use Carbon\Carbon;
use Orchid\Screen\Actions\Button;
use Orchid\Screen\Actions\Link;
use Orchid\Screen\Fields\Input;
use Orchid\Screen\Fields\Matrix;
use Orchid\Screen\Fields\Select;
use Orchid\Screen\Fields\TextArea;
use Orchid\Support\Facades\Layout;
use App\DRX\Screens\SecuritySRQScreen;


class PermanentCarScreen extends SecuritySRQScreen
{


    // Тип документа в сервисе интеграции, например IOfficialDocuments
    public static $EntityType = "IServiceRequestsPermanentPass4Cars";
    public static $Title = "Заявка на оформление постоянного автопропуска";

    public function ExpandFields()
    {
        $ExpandFields = ['ParkingPlace', 'Cars'];
        return array_merge(parent::ExpandFields(), $ExpandFields);
    }

    public function CollectionFields()
    {
        return array_merge(['Cars'], parent::CollectionFields()) ; // TODO: Change the autogenerated stub
    }

    public function NewEntity()
    {
        $entity = parent::NewEntity();
        $entity['Action'] = "NewPass";
        $entity['ValidFrom'] = Carbon::today()->addDay();
        $entity['ValidTill'] = Carbon::today()->addDay(365);
        return $entity;
    }

    public function commandBar(): iterable
    {
        $commandBar = parent::commandBar();
        if (($this->entity["RequestState"] ?? '') === 'Approved') {
            $commandBar[] = Link::make("Изменить пропуск")->route('drx.ChangePermanentPass4Car', ['pass' => $this->entity['Id']]);
        }
        return $commandBar;
    }

    // Описывает макет экрана
    public function layout(): iterable
    {
        $layout = parent::layout();
        $layout[] = Layout::rows([
            Select::make('entity.ParkingPlace.Id')
                ->title('Парковочное место')->horizontal()
                ->empty()
                ->disabled($this->readOnly)->required()
                ->help('Если в списке отображаются не все ваши парковочные места, обратитесь в администрацию БЦ')
                ->options(Databooks::GetParkingPlaces()),
            Matrix::make('entity.Cars')
                ->title('Автомобили, которые нужно добавить в пропуск. Для каждого будет изготовлен ламинированный пропуск.')->horizontal()
                ->columns(['Модель'=>'Model', 'Номер'=>'Number'])
                ->disabled($this->readOnly)->required(),
            TextArea::make('entity.Visitors')
                ->title('Водители')->horizontal()
                ->rows(3)
        ]);
        $layout[] = Layout::rows([TextArea::make('entity.Note')
            ->title("Примечание")->rows(10)->horizontal()
            ->disabled($this->readOnly)]);
        return $layout;
    }

    public function BlockPass()
    {
        $this->entity['RequestState'] = 'Done';
        $this->entity['VaildTill'] = Carbon::today()->addDays(-1);
        parent::SubmitToApproval('Заявка на блокировку пропуска отправлена');
    }
}
